#! /usr/bin/env python3

from pi_walk_slope.joint_param import main
import sys
import os
from termcolor import colored



USAGE = """ usage: run fn_gaitEvent fn_joint output_folder
-->fn_gaitEvent: file containing the gait event information
-->fn_joint: file containing the joint angles measured
-->output_folder: folder where the generated PI yaml files will be stored
"""


if __name__ == '__main__':

    if len(sys.argv) != 4:
        print(colored("Wrong input parameters !", "red"))
        print(colored(USAGE, "yellow"))
        sys.exit(-1)

    fn_gait = sys.argv[1]
    fn_joint = sys.argv[2]
    folder_out = sys.argv[3]

    if not os.path.exists(fn_gait):
        print(colored("Input file {} does not exist".format(fn_gait), "red"))
        sys.exit(-1)

    if not os.path.isfile(fn_gait):
        print(colored("Input path {} is not a file".format(fn_gait), "red"))
        sys.exit(-1)

    if not os.path.exists(fn_joint):
        print(colored("Input file {} does not exist".format(fn_joint), "red"))
        sys.exit(-1)

    if not os.path.isfile(fn_joint):
        print(colored("Input path {} is not a file".format(fn_joint), "red"))
        sys.exit(-1)
    if not os.path.exists(folder_out):
        print(colored(
            "Output folder {} does not exist".format(folder_out),
            "red"))
        sys.exit(-1)

    if not os.path.isdir(folder_out):
        print(colored(
            "{} is not a folder".format(folder_out),
            "red"))
        sys.exit(-1)
    sys.exit(main(fn_gait, fn_joint, folder_out))
